services:
  # === Service: S3-compatible object storage
  minio:
    image: minio/minio:latest
    container_name: tp-minio
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - tp-network

  # === Service: Data base (postgres)
  db:
    image: postgres
    container_name: ${LOCAL_PGDB_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    ports:
      - 5433:5432
    volumes:
      ## Persistent database data
      - local_pgdata:/var/lib/postgresql
    networks:
      - tp-network

  # === Service: Web-based graphical interface for interacting with the database (pgadmin)
  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    container_name: pgadmin_gui
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8080:80
    volumes:
      - local_pgadmin:/var/lib/pgadmin
    networks:
      - tp-network

volumes:
  minio_data:
  local_pgdata:
  local_pgadmin:

networks:
  tp-network:
    driver: bridge